package com.mkpro.domain.model

/**
 * Calculated position for rendering a key on screen.
 * Generated by LayoutEngine based on container dimensions.
 */
data class KeyPosition(
    val key: KeyDefinition,
    val x: Float,
    val y: Float,
    val width: Float,
    val height: Float
) {
    /**
     * Checks if a touch point falls within this key's bounds.
     */
    fun contains(touchX: Float, touchY: Float): Boolean {
        return touchX >= x && touchX <= x + width &&
               touchY >= y && touchY <= y + height
    }

    val centerX: Float get() = x + width / 2f
    val centerY: Float get() = y + height / 2f
}
